name       : perl-list-someutils
version    : '0.59'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/List-SomeUtils-0.59.tar.gz : fab30372e4c67bf5a46062da38d1d0c8756279feada866eb439fa29571a2dc7b
homepage   : https://metacpan.org/pod/List::SomeUtils
license    : Artistic-2.0
component  : programming.perl
summary    : provides some trivial but commonly needed functionality on lists which is not going to go into ListUtil
description: |
    provides some trivial but commonly needed functionality on lists which is not going to go into ListUtil
rundeps    :
    - perl-module-implementation
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
