name       : perl-list-someutils
version    : '0.56'
release    : 5
source     :
    - https://www.cpan.org/authors/id/D/DR/DROLSKY/List-SomeUtils-0.56.tar.gz : eaa7d99ce86380c0389876474c8eb84acc0a6bfeef1b0fc23a292592de6f89f7
license    : GPL-2.0
component  : programming.perl
summary    : provides some trivial but commonly needed functionality on lists which
    is not going to go into ListUtil
description: |
    provides some trivial but commonly needed functionality on lists which is not going to go into ListUtil
rundeps    :
    - perl-module-implementation
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
